### ISSUE TITLE
[invalid] Selecciona el primer plan de estudios

### ISSUE THREAD

**Issue by eanorambuena** [open-source-uc/auto-ramos#1]
# Selecciona el primer plan de estudios
#### Etiquetas sugeridas
label: invalid, label: bug 
#### Podría pedir al usuario indicar el plan de estudios deseado si tiene más un plan de estudios.

**Comment by Dyotson** [comment]
Estamos viendo como implementarlo, el problema que hay es que solo te deja seleccionar el plan de estudios cuando se abre el banner, por lo cual gastaria tiempo en tomar ramos seleccionar el plan de estudio... Por ahora solo se usara el primer plan que aparezca
